name: Release a Haskell package repository

description:
  Perform automatic version management and publish a package on Hackage.

inputs:

  hackage-token:
    description: |
      Authentication token for Hackage. You can generate it at [your Hackage account management page](http://hackage.haskell.org/users/account-management) and provide it via Github Actions Secrets.
    required: true

  version-bump-place:
    description: |
      Index of the bumped version place.

      E.g., `2` points to `x` in `0.1.x.0`.

      To determine the place from a branch name you can use the following expression:

      ```
      ${{ fromJSON('{"supermajor":0,major":1,"minor":2,"patch":3}')[github.ref_name] }}
      ```
    required: true

  main-branch:
    description:
      The name of your main branch to merge the version changes to. E.g., "main" or "master". Defaults to "main".
    default: main

runs:
  using: composite
  steps:

    - name: Bump package version
      uses: nikita-volkov/edit-cabal-version.github-action@v1.1.1
      with:
        mode: bump
        bump-place: ${{ inputs.version-bump-place }}
      id: bump-cabal-version

    - name: Ensure no according tag exists
      uses: nikita-volkov/fail-if-tag-exists.github-action@v1.0.0
      with:
        tag: ${{ steps.bump-cabal-version.outputs.after }}

    - name: Publish on Hackage
      uses: nikita-volkov/publish-to-hackage.github-action@v2.0.1
      with:
        token: ${{ inputs.hackage-token }}
        publish: true

    - name: Commit the version update
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Set package version to ${{ steps.bump-cabal-version.outputs.after }}
        file_pattern: |
          *.cabal
      id: commit

    - name: Tag
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag: ${{ steps.bump-cabal-version.outputs.after }}
        tag_prefix:
        commit_sha: ${{ steps.commit.outputs.commit_hash }}

    - name: Merge to master
      uses: devmasx/merge-branch@1.4.0
      with:
        type: now
        from_branch: ${{ github.ref_name }}
        target_branch: ${{ inputs.main-branch }}
        github_token: ${{ github.token }}
        message: Set package version to ${{ steps.bump-cabal-version.outputs.after }}
